### ISSUE TITLE
Jitter problem.

### ISSUE THREAD

**Issue by zhanglonghao1992** [SamsungLabs/rome#8]
Hi～
When I tested it on videos, I found that there was obvious inter frame jitter in the result, as shown below.

https://user-images.githubusercontent.com/17874285/182549247-392a5e21-068a-4a59-8d24-13ebe19ccc50.mp4

Why does it cause such obvious jitter? Is there any way to optimize it.

**Comment by khakhulin** [comment]
Do you use DECA camera or a camera from the mobile-net?

**Comment by zhanglonghao1992** [comment]
> 

I use the default settings in `infer.py`.

**Comment by khakhulin** [comment]
So, it should be ok, with the natural jitter from the deca (see video on the site).

**Comment by nlml** [comment]
@khakhulin Is there a way to reduce this jitter? What is the 'camera from the mobile-net' that you refer to?

**Comment by khakhulin** [comment]
@nlml I just suggest using the original camera from the DECA, not the distiller version. I think if the jitter is a real problem. then you need to optimize the sequence of the keypoints itself. Since original DECA doesn't guarantee temporal consistency if you run it with per-frame expression transfer.
